// Generated by errata-gen. Do not edit.

export const errataBySlug = {
  "aviation-specification-completeness": {
    "slug": "aviation-specification-completeness",
    "linkedinUrl": null,
    "vnextMarkdownUrl": "/papers/aviation-specification-completeness/vnext.md",
    "vnextPdfUrl": "/papers/aviation-specification-completeness/vnext.pdf",
    "errata": []
  },
  "specification-as-quality-gate": {
    "slug": "specification-as-quality-gate",
    "linkedinUrl": null,
    "vnextMarkdownUrl": "/papers/specification-as-quality-gate/vnext.md",
    "vnextPdfUrl": "/papers/specification-as-quality-gate/vnext.pdf",
    "errata": []
  },
  "structural-quality-gaps-agents-md": {
    "slug": "structural-quality-gaps-agents-md",
    "linkedinUrl": null,
    "vnextMarkdownUrl": "/papers/structural-quality-gaps-agents-md/vnext.md",
    "vnextPdfUrl": "/papers/structural-quality-gaps-agents-md/vnext.pdf",
    "errata": []
  }
} as const;
